const laoLabels: Record<string, string> = {
  "All Stations": "ທຸກສະຖານີ",
  "Kitchen": "ຄົວ",
  "Bar": "ບາ",
  "Bakery": "ເບເກີຣີ",
  "Pass": "ຈຸດສົ່ງອາຫານ",
  "Station": "ສະຖານີ",
  "Order Type": "ປະເພດອໍເດີ",
  "Items": "ລາຍການ",
  "kitchen": "ຄົວ",
  "bar": "ບາ",
  "bakery": "ເບເກີຣີ",
  "pass": "ຈຸດສົ່ງອາຫານ",
  "new": "ໃໝ່",
  "preparing": "ກຳລັງກຽມ",
  "ready": "ພ້ອມ",
  "New": "ໃໝ່",
  "Preparing": "ກຳລັງກຽມ",
  "Ready": "ພ້ອມ",
  "High": "ດ່ວນ",
  "Normal": "ປົກກະຕິ",
  "Dine In": "ນັ່ງກິນທີ່ຮ້ານ",
  "Take Away": "ສັ່ງກັບບ້ານ",
  "Counter": "ເຄົາເຕີ",
  "Table": "ໂຕະ",
  "Walk-in Customer": "ລູກຄ້າທົ່ວໄປ",
  "Online Order": "ອໍເດີ Online",
  "Delivery Partner": "ຄູ່ຄ້າຈັດສົ່ງ",
  "Unassigned": "ຍັງບໍ່ມອບໝາຍ",
  "Pass Station": "ສະຖານີສົ່ງອາຫານ",
  "Longest Waiting": "ລໍຖ້າດົນສຸດ",
  "Priority First": "ດ່ວນກ່ອນ",
  "Newest First": "ໃໝ່ສຸດກ່ອນ",
  "elapsed": "ຜ່ານໄປ",
  "Assigned:": "ມອບໝາຍ:",
  "Note:": "ໝາຍເຫດ:",
  "Start Preparing": "ເລີ່ມກຽມ",
  "Mark Ready": "ໝາຍວ່າພ້ອມ",
  "Complete Pickup": "ຮັບສຳເລັດ",
  "View Detail": "ເບິ່ງລາຍລະອຽດ",
  "Recall to Preparing": "ດຶງກັບໄປກຳລັງກຽມ",
  "Kitchen Settings": "ຕັ້ງຄ່າຄົວ",
  "Station filter and display behavior": "ກັ່ນຕອງສະຖານີ ແລະ ຮູບແບບການສະແດງ",
  "Station Filter": "ກັ່ນຕອງສະຖານີ",
  "Sound Alerts": "ສຽງແຈ້ງເຕືອນ",
  "Play sound for every new order": "ເປີດສຽງສຳລັບອໍເດີໃໝ່ທຸກຄັ້ງ",
  "Show Item Notes": "ສະແດງໝາຍເຫດລາຍການ",
  "Display modifiers and preparation notes": "ສະແດງ modifiers ແລະ ໝາຍເຫດການກຽມ",
  "Show Elapsed Time": "ສະແດງເວລາລໍຖ້າ",
  "Highlight waiting time on tickets": "ເນັ້ນເວລາລໍຖ້າໃນ ticket",
  "Auto Refresh": "ໂຫຼດໃໝ່ອັດຕະໂນມັດ",
  "Compact Ticket Cards": "ບັດ ticket ແບບກະທັດຮັດ",
  "Show denser cards for busy service": "ສະແດງບັດແບບແໜ້ນໃນຊ່ວງວຽກຫຼາຍ",
  "Auto Print Tickets": "ພິມ ticket ອັດຕະໂນມັດ",
  "Send tickets to station printer automatically": "ສົ່ງ ticket ໄປ Printer ຂອງສະຖານີອັດຕະໂນມັດ",
  "Large Print Text": "ຕົວອັກສອນພິມຂະໜາດໃຫຍ່",
  "Use larger text on printed kitchen tickets": "ໃຊ້ຕົວອັກສອນໃຫຍ່ໃນ ticket ຄົວທີ່ພິມ",
  "Reset": "ຣີເຊັດ",
  "Save Settings": "ບັນທຶກການຕັ້ງຄ່າ",
  "Pad Thai (Chicken)": "ຜັດໄທໄກ່",
  "Fresh Spring Roll (Pork)": "ປໍເປີຍສົດໝູ",
  "Lime Soda": "ໂຊດາໝາກນາວ",
  "Tom Yum Goong": "ຕົ້ມຍຳກຸ້ງ",
  "Green Tea Matcha Latte": "ມັດຊະລາເຕ້ຊາຂຽວ",
  "Steamed Rice": "ເຂົ້າສວຍ",
  "Mango Sticky Rice": "ເຂົ້າໜຽວມ່ວງ",
  "Croissant": "ຄຣົວຊອງ",
  "Chocolate Muffin": "ມັບຟິນຊັອກໂກແລັດ",
  "Iced Americano": "ອາເມຣິກາໂນເຢັນ",
  "Iced Latte": "ລາເຕ້ເຢັນ",
  "Blueberry Cheesecake": "ຊີສເຄັກບລູເບີຣີ",
  "Paper Cup 12oz": "ຈອກເຈ້ຍ 12oz",
  "Thai Iced Tea": "ຊາໄທເຢັນ",
  "Khao Piak Sen": "ເຂົ້າປຽກເສັ້ນ",
  "Massaman Curry (Chicken)": "ແກງມັດສະມັນໄກ່",
  "Jasmine Rice": "ເຂົ້າຫອມມະລິ",
  "Coconut Smoothie": "ນ້ຳປັ່ນມະພ້າວ"
};

export function lo(value: string) {
  return laoLabels[value] ?? value.replace(/^Table /, "ໂຕະ ");
}
