const laoLabels: Record<string, string> = {
  "Service Staff": "ພະນັກງານບໍລິການ",
  "Order Device 03": "ອຸປະກອນຮັບອໍເດີ 03",
  "All": "ທັງໝົດ",
  "Coffee": "ກາເຟ",
  "coffee": "ກາເຟ",
  "Tea": "ຊາ",
  "tea": "ຊາ",
  "non-coffee": "ບໍ່ແມ່ນກາເຟ",
  "pastry": "ເບເກີຣີ",
  "snacks": "ອາຫານ",
  "beverages": "ເຄື່ອງດື່ມ",
  "Bakery": "ເບເກີຣີ",
  "Meals": "ອາຫານ",
  "Add-ons": "ເພີ່ມເຕີມ",
  "Iced Latte": "ລາເຕ້ເຢັນ",
  "Americano": "ອາເມຣິກາໂນ",
  "Cappuccino": "ຄາປູຊິໂນ",
  "Thai Milk Tea": "ຊານົມໄທ",
  "Croissant": "ຄຣົວຊອງ",
  "Chocolate Cake": "ເຄັກຊັອກໂກແລັດ",
  "Club Sandwich": "ແຊນວິດຄລັບ",
  "Mineral Water": "ນ້ຳດື່ມ",
  "Cola Can": "ໂຄລາກະປ໋ອງ",
  "Sprite Can": "ສະໄປຣທ໌ກະປ໋ອງ",
  "Orange Juice": "ນ້ຳສົ້ມ",
  "Green Tea": "ຊາຂຽວ",
  "Popular": "ນິຍົມ",
  "New": "ໃໝ່",
  "Top Pick": "ແນະນຳ",
  "Regular Size": "ຂະໜາດປົກກະຕິ",
  "Full Cream Milk": "ນົມ Full Cream",
  "Less Sugar": "ຫວານນ້ອຍ",
  "Normal": "ປົກກະຕິ",
  "Regular Ice": "ນ້ຳກ້ອນປົກກະຕິ",
  "No Ice": "ບໍ່ໃສ່ນ້ຳກ້ອນ",
  "Buttery": "ຫອມເນີຍ",
  "Less sugar, extra shot": "ຫວານນ້ອຍ, ເພີ່ມ shot",
  "Tables": "ໂຕະ",
  "Menu": "ເມນູ",
  "Orders": "ອໍເດີ",
  "Profile": "ໂປຣໄຟລ໌",
  "Online": "ອອນລາຍ",
  "Branch": "ສາຂາ",
  "Staff": "ພະນັກງານ",
  "Shift": "ກະ",
  "Morning": "ກະເຊົ້າ",
  "Staff Login": "ເຂົ້າລະບົບພະນັກງານ",
  "Welcome back, Somchai!": "ຍິນດີຕ້ອນຮັບກັບ, Somchai!",
  "Let's get ready to take great orders.": "ກຽມພ້ອມຮັບອໍເດີຢ່າງດີ.",
  "Date": "ວັນທີ",
  "Time": "ເວລາ",
  "Role": "ບົດບາດ",
  "Employee ID": "ລະຫັດພະນັກງານ",
  "Today's Shift": "ກະວຽກມື້ນີ້",
  "Morning Shift": "ກະເຊົ້າ",
  "Main Floor": "ຊັ້ນຫຼັກ",
  "Quick Branch Switch": "ປ່ຽນສາຂາດ່ວນ",
  "Branch management opens in admin.": "ການຈັດການສາຂາຈະເປີດໃນ Admin.",
  "Manage Branches": "ຈັດການສາຂາ",
  "Device": "ອຸປະກອນ",
  "Connection": "ການເຊື່ອມຕໍ່",
  "Login & Start Taking Orders": "ເຂົ້າລະບົບ ແລະ ເລີ່ມຮັບອໍເດີ",
  "Staff QR scanner ready.": "ພ້ອມສະແກນ QR ພະນັກງານ.",
  "Scan Staff QR": "ສະແກນ QR ພະນັກງານ",
  "Take Order": "ຮັບອໍເດີ",
  "Guests": "ລູກຄ້າ",
  "Search menu items": "ຄົ້ນຫາລາຍການເມນູ",
  "Select Table": "ເລືອກໂຕະ",
  "All Areas": "ທຸກໂຊນ",
  "Number of Guests": "ຈຳນວນລູກຄ້າ",
  "Continue with": "ດຳເນີນຕໍ່ກັບ",
  "Seats": "ບ່ອນນັ່ງ",
  "Review Order": "ກວດອໍເດີ",
  "Table": "ໂຕະ",
  "Type": "ປະເພດ",
  "No items in this order yet.": "ຍັງບໍ່ມີລາຍການໃນອໍເດີນີ້.",
  "Subtotal": "ຍອດກ່ອນຫຼຸດ",
  "Service Charge (5%)": "ຄ່າບໍລິການ (5%)",
  "Discount": "ສ່ວນຫຼຸດ",
  "Total": "ລວມທັງໝົດ",
  "Walk-in Customer": "ລູກຄ້າທົ່ວໄປ",
  "No member attached": "ບໍ່ມີສະມາຊິກຜູກໄວ້",
  "Add": "ເພີ່ມ",
  "Save Draft": "ບັນທຶກຮ່າງ",
  "Send Order": "ສົ່ງອໍເດີ",
  "Note": "ໝາຍເຫດ",
  "Cart": "ກະຕ່າ",
  "View items": "ເບິ່ງລາຍການ",
  "Customize Item": "ປັບແຕ່ງລາຍການ",
  "Size": "ຂະໜາດ",
  "Small": "ນ້ອຍ",
  "Medium": "ກາງ",
  "Large": "ໃຫຍ່",
  "Sugar Level": "ລະດັບນ້ຳຕານ",
  "No Sugar": "ບໍ່ໃສ່ນ້ຳຕານ",
  "Less Sweet": "ຫວານນ້ອຍ",
  "Extra Sweet": "ຫວານຫຼາຍ",
  "Ice Level": "ລະດັບນ້ຳກ້ອນ",
  "Less Ice": "ນ້ຳກ້ອນນ້ອຍ",
  "Extra Ice": "ເພີ່ມນ້ຳກ້ອນ",
  "None": "ບໍ່ມີ",
  "Less": "ນ້ອຍ",
  "More Ice": "ນ້ຳກ້ອນຫຼາຍ",
  "Extra Shot": "ເພີ່ມ shot",
  "Whipped Cream": "ວິບຄຣີມ",
  "Oat Milk": "ນົມ Oat",
  "Add note for kitchen or bar...": "ເພີ່ມໝາຍເຫດໃຫ້ຄົວ ຫຼື ບາ...",
  "On Shift": "ຢູ່ໃນກະ",
  "Settings": "ຕັ້ງຄ່າ",
  "Branch & Device": "ສາຂາ ແລະ ອຸປະກອນ",
  "View branch details and device info": "ເບິ່ງລາຍລະອຽດສາຂາ ແລະ ອຸປະກອນ",
  "Printer Settings": "ຕັ້ງຄ່າ Printer",
  "Manage printers and print options": "ຈັດການ Printer ແລະ ຕົວເລືອກພິມ",
  "Sound & Notifications": "ສຽງ ແລະ ແຈ້ງເຕືອນ",
  "Configure sounds and alerts": "ຕັ້ງຄ່າສຽງ ແລະ alert",
  "Language": "ພາສາ",
  "Change app language": "ປ່ຽນພາສາແອັບ",
  "English": "ລາວ",
  "System": "ລະບົບ",
  "Help Center": "ສູນຊ່ວຍເຫຼືອ",
  "FAQs and support": "FAQ ແລະ support",
  "Sync Status": "ສະຖານະ Sync",
  "Keep data in sync across devices": "ຮັກສາຂໍ້ມູນໃຫ້ Sync ຂ້າມອຸປະກອນ",
  "About App": "ກ່ຽວກັບແອັບ",
  "App information and version": "ຂໍ້ມູນແອັບ ແລະ version",
  "Switch Branch": "ປ່ຽນສາຂາ",
  "Logout": "ອອກຈາກລະບົບ",
  "Order Sent": "ສົ່ງອໍເດີແລ້ວ",
  "Order sent successfully": "ສົ່ງອໍເດີສຳເລັດ",
  "The kitchen and bar have received the order for Table": "ຄົວ ແລະ ບາໄດ້ຮັບອໍເດີສຳລັບໂຕະ",
  "Order No.": "ເລກອໍເດີ",
  "Sent Time": "ເວລາສົ່ງ",
  "Back to Menu": "ກັບໄປເມນູ",
  "View Active Orders": "ເບິ່ງອໍເດີທີ່ເປີດຢູ່",
  "Start New Order": "ເລີ່ມອໍເດີໃໝ່",
  "Active Orders": "ອໍເດີທີ່ກຳລັງເປີດ",
  "Active": "ກຳລັງເປີດ",
  "Ready": "ພ້ອມ",
  "Open Bills": "ບິນທີ່ຍັງເປີດ",
  "Search table or order": "ຄົ້ນຫາໂຕະ ຫຼື ອໍເດີ",
  "Preparing": "ກຳລັງກຽມ",
  "Sent": "ສົ່ງແລ້ວ",
  "Ready to Serve": "ພ້ອມເສີບ",
  "Waiting Bill": "ລໍຖ້າອອກບິນ",
  "Dine In": "ນັ່ງກິນທີ່ຮ້ານ",
  "Take Away": "ສັ່ງກັບບ້ານ",
  "items": "ລາຍການ",
  "Open": "ເປີດ",
  "Mark Served": "ໝາຍວ່າເສີບແລ້ວ",
  "Generate Bill": "ສ້າງບິນ",
  "Add Item": "ເພີ່ມສິນຄ້າ",
  "Available": "ວ່າງ",
  "Occupied": "ມີລູກຄ້າ",
  "Reserved": "ຈອງໄວ້",
  "Indoor": "ພາຍໃນ",
  "Outdoor": "ພາຍນອກ",
  "VIP Room": "ຫ້ອງ VIP",
  "Terrace": "ລານນອກ"
};

export function lo(value: string) {
  return laoLabels[value] ?? value;
}
