import type { ReactNode } from "react";

const laoLabels: Record<string, string> = {
  Dashboard: "ແດຊບອດ",
  POS: "POS",
  Orders: "ອໍເດີ",
  Appointments: "ນັດໝາຍ",
  Calendar: "ປະຕິທິນ",
  Bookings: "ການຈອງ",
  "Walk-in": "ລູກຄ້າ Walk-in",
  Items: "ສິນຄ້າ",
  Services: "ບໍລິການ",
  Categories: "ໝວດໝູ່",
  "Table Map": "ແຜນຜັງໂຕະ",
  Modifiers: "ຕົວເລືອກເພີ່ມ",
  "Barista Queue": "ຄິວ Barista",
  "Pickup Display": "ຈໍຮັບອໍເດີ",
  "Happy Hour": "Happy Hour",
  "Cafe Daily View": "ພາບລວມຮ້ານກາເຟ",
  Reservations: "ການຈອງໂຕະ",
  "Kitchen Courses": "ລຳດັບຄົວ",
  "Split Bill": "ແຍກບິນ",
  "Service Charge": "ຄ່າບໍລິການ",
  "Merge / Transfer": "ລວມ / ຍ້າຍ",
  "End of Day": "ປິດຮອບມື້",
  "Staff Schedule": "ຕາຕະລາງພະນັກງານ",
  Packages: "ແພັກເກດ",
  "Deposit Policy": "ນະໂຍບາຍມັດຈຳ",
  "Beauty Daily": "ພາບລວມຮ້ານຄວາມງາມ",
  Rooms: "ຫ້ອງ",
  "Room Calendar": "ປະຕິທິນຫ້ອງ",
  "Front Desk": "ຟຣອນດ໌ເດສກ໌",
  "Check-in": "Check-in",
  "Check-out": "Check-out",
  Guests: "ແຂກ",
  "Room Settings": "ຕັ້ງຄ່າຫ້ອງ",
  Housekeeping: "ແມ່ບ້ານ",
  "Guest Folio": "ບັນຊີແຂກ",
  Inventory: "ສະຕັອກ",
  "Stock Movements": "ການເຄື່ອນໄຫວສະຕັອກ",
  "Stock Count": "ນັບສະຕັອກ",
  "Goods Receiving": "ຮັບສິນຄ້າ",
  Returns: "ຄືນສິນຄ້າ",
  "Low Stock / Expiry": "ສະຕັອກຕ່ຳ / ໃກ້ໝົດອາຍຸ",
  "Barcode Labels": "ປ້າຍ Barcode",
  Suppliers: "ຜູ້ສະໜອງ",
  Customers: "ລູກຄ້າ",
  Loyalty: "ສະສົມແຕ້ມ",
  Promotions: "ໂປຣໂມຊັນ",
  "Roles & Permissions": "ບົດບາດ ແລະ ສິດ",
  Branches: "ສາຂາ",
  Reports: "ລາຍງານ",
  "Receipt/Bill": "ໃບຮັບເງິນ / ບິນ",
  Branding: "ແບຣນດ໌",
  "Payment Methods": "ວິທີຊຳລະ",
  Devices: "ອຸປະກອນ",
  Modules: "ໂມດູນ",
  "Import/Export": "ນຳເຂົ້າ / ສົ່ງອອກ",
  Support: "ຊ່ວຍເຫຼືອ",
  "Audit Logs": "ບັນທຶກກວດສອບ",
  Settings: "ຕັ້ງຄ່າ",
  "Need Help?": "ຕ້ອງການຊ່ວຍເຫຼືອ?",
  "Visit our Help Center for guides and tutorials.":
    "ເຂົ້າໄປສູນຊ່ວຍເຫຼືອເພື່ອອ່ານຄູ່ມື ແລະ ວິທີໃຊ້ງານ.",
  "Go to Help Center": "ໄປສູນຊ່ວຍເຫຼືອ",
  "Open POS": "ເປີດ POS",
  "Business Owner": "ເຈົ້າຂອງທຸລະກິດ",
  "Search items, orders, customers...": "ຄົ້ນຫາສິນຄ້າ, ອໍເດີ, ລູກຄ້າ...",
  Search: "ຄົ້ນຫາ",
  Filter: "ກັ່ນຕອງ",
  Category: "ໝວດໝູ່",
  Status: "ສະຖານະ",
  Branch: "ສາຂາ",
  Type: "ປະເພດ",
  Notes: "ໝາຍເຫດ",
  "Target Audience": "ກຸ່ມເປົ້າໝາຍ",
  "Date Range": "ຊ່ວງວັນທີ",
  Export: "ສົ່ງອອກ",
  View: "ເບິ່ງ",
  Edit: "ແກ້ໄຂ",
  More: "ເພີ່ມເຕີມ",
  "Quick Actions": "ການດຳເນີນການດ່ວນ",
  "Showing 1 to 8 of 342 records": "ສະແດງ 1 ຫາ 8 ຈາກ 342 ລາຍການ",
  "Showing 1 to 8 of 28 records": "ສະແດງ 1 ຫາ 8 ຈາກ 28 ລາຍການ",
  "10 / page": "10 / ໜ້າ",
  Active: "ເປີດໃຊ້",
  Inactive: "ປິດໃຊ້",
  Ready: "ພ້ອມ",
  Pending: "ລໍຖ້າ",
  Completed: "ສຳເລັດ",
  Cancelled: "ຍົກເລີກ",
  "In Progress": "ກຳລັງດຳເນີນ",
  Paid: "ຈ່າຍແລ້ວ",
  Partial: "ຈ່າຍບາງສ່ວນ",
  Unpaid: "ຍັງບໍ່ຈ່າຍ",
  Debt: "ຕິດໜີ້",
  Clear: "ປົກກະຕິ",
  "Retail Customer": "ລູກຄ້າຂາຍຍ່ອຍ",
  "Wholesale Customer": "ລູກຄ້າຂາຍສົ່ງ",
  Reseller: "ຜູ້ຂາຍຕໍ່",
  VIP: "VIP",
  Retail: "ຂາຍຍ່ອຍ",
  Wholesale: "ຂາຍສົ່ງ",
  Purchase: "ຊື້ເຂົ້າ",
  Return: "ຄືນສິນຄ້າ",
  Delivery: "ຈັດສົ່ງ",
  "Dine In": "ນັ່ງກິນທີ່ຮ້ານ",
  "Take Away": "ສັ່ງກັບບ້ານ",
  "Walk-in Customer": "ລູກຄ້າທົ່ວໄປ",
  "Default Retail": "ລາຄາຂາຍຍ່ອຍພື້ນຖານ",
  "Cafe Wholesale": "ລາຄາສົ່ງຮ້ານກາເຟ",
  "Bakery Wholesale": "ລາຄາສົ່ງເບເກີຣີ",
  "Beverage Reseller": "ລາຄາຜູ້ຂາຍຕໍ່ເຄື່ອງດື່ມ",
  "VIP Retail": "ລາຄາ VIP",
  "All Branches": "ທຸກສາຂາ",
  "All Statuses": "ທຸກສະຖານະ",
  "All Categories": "ທຸກໝວດໝູ່",
  "All Customer Types": "ທຸກປະເພດລູກຄ້າ",
  "All Payment Status": "ທຸກສະຖານະຊຳລະ",
  "All Debt Status": "ທຸກສະຖານະໜີ້",
  "All Delivery Status": "ທຸກສະຖານະຈັດສົ່ງ",
  "All Price Types": "ທຸກປະເພດລາຄາ",
  "All Price Lists": "ທຸກລາຍການລາຄາ",
  "All Types": "ທຸກປະເພດ",
  "All Locations": "ທຸກຕຳແໜ່ງ",
  "All Suppliers": "ທຸກຜູ້ສະໜອງ",
  "All Status": "ທຸກສະຖານະ",
  "New Stock Count": "ສ້າງການນັບສະຕັອກ",
  "Receive Goods": "ຮັບສິນຄ້າ",
  "Process Return": "ດຳເນີນການຄືນ",
  "Print Labels": "ພິມປ້າຍ",
  "Needs approval": "ຕ້ອງອະນຸມັດ",
  "List View": "ເບິ່ງແບບລາຍການ",
  Day: "ມື້",
  "Review & Pay": "ກວດສອບ & ຊຳລະ",
  "By Guest": "ຕາມແຂກ",
  "By Item": "ຕາມລາຍການ",
  "Add Guest": "ເພີ່ມແຂກ",
  "Total Amount": "ຍອດລວມ",
  "Total Payable": "ຍອດຕ້ອງຊຳລະ",
  "Transfer Table": "ຍ້າຍໂຕະ",
  Available: "ວ່າງ",
  "Close Day": "ປິດມື້",
  "Save Settings": "ບັນທຶກການຕັ້ງຄ່າ",
  "Create Appointment": "ສ້າງນັດໝາຍ",
  "Add Service": "ເພີ່ມບໍລິການ",
  "Add Shift": "ເພີ່ມກະ",
  "New Package": "ແພັກເກດໃໝ່",
  "Last package": "ແພັກເກດຫຼ້າສຸດ",
  "Save Deposit Policy": "ບັນທຶກນະໂຍບາຍມັດຈຳ",
  "Cancellation Rule": "ກົດການຍົກເລີກ",
  "New Booking": "ສ້າງການຈອງ",
  "Add Room": "ເພີ່ມຫ້ອງ",
  "Next: Guest Info": "ຕໍ່ໄປ: ຂໍ້ມູນແຂກ",
  "Complete Check-in": "Check-in ໃຫ້ສຳເລັດ",
  "Complete Check-out": "Check-out ໃຫ້ສຳເລັດ",
  "Post Charge": "ເພີ່ມຄ່າໃຊ້ຈ່າຍ",
  "Save Policy": "ບັນທຶກນະໂຍບາຍ",
  "Save Promotion": "ບັນທຶກໂປຣໂມຊັນ",
  Reset: "ຣີເຊັດ",
  "View All": "ເບິ່ງທັງໝົດ",
  "View all": "ເບິ່ງທັງໝົດ",
  Redemptions: "ການແລກແຕ້ມ",
  "Sales Overview": "ພາບລວມຍອດຂາຍ",
  "This Week": "ອາທິດນີ້",
  "Gross Sales (This Week)": "ຍອດຂາຍລວມ (ອາທິດນີ້)",
  Item: "ລາຍການ",
  Sold: "ຂາຍແລ້ວ",
  Revenue: "ລາຍຮັບ",
  "Current Stock": "ສະຕັອກປັດຈຸບັນ",
  "Sales (This Week)": "ຍອດຂາຍ (ອາທິດນີ້)",
  "vs Last Week": "ທຽບກັບອາທິດກ່ອນ",
  "Branch Form": "ຟອມສາຂາ",
  "Save & Continue": "ບັນທຶກ & ດຳເນີນຕໍ່",
  "Save Changes": "ບັນທຶກການແກ້ໄຂ",
  Save: "ບັນທຶກ",
  Cancel: "ຍົກເລີກ",
  "Create Order": "ສ້າງ Order",
  "Create Reservation": "ສ້າງ Reservation",
  "Create Course": "ສ້າງ Course",
  "Create Modifier Group": "ສ້າງ Modifier Group",
  "Create Happy Hour": "ສ້າງ Happy Hour",
  "Floor / Room": "ຊັ້ນ / ຫ້ອງ",
  "Deposit Required": "ຕ້ອງມັດຈຳ",
  Staff: "ພະນັກງານ",
  "Manager - 11:35 PM": "ຜູ້ຈັດການ - 11:35 PM",
  "Add-ons": "ຕົວເລືອກເພີ່ມ",
  "20% Off": "ຫຼຸດ 20%",
  "May 12 - May 18, 2025": "12 - 18 ພຶດສະພາ 2025",
  "May 18, 2025": "18 ພຶດສະພາ 2025",
  "May 2025": "ພຶດສະພາ 2025",
  Mo: "ຈ",
  Tu: "ອ",
  We: "ພ",
  Th: "ພຫ",
  Fr: "ສ",
  Sa: "ສອ",
  Su: "ອາ",
  "Sun 18": "ອາ 18",
  "Mon 19": "ຈ 19",
  "Tue 20": "ອ 20",
  "Wed 21": "ພ 21",
  "Thu 22": "ພຫ 22",
  "Fri 23": "ສ 23",
  "Sat 24": "ສອ 24",
  "May 12": "12 ພຶດສະພາ",
  "May 13": "13 ພຶດສະພາ",
  "May 14": "14 ພຶດສະພາ",
  "May 15": "15 ພຶດສະພາ",
  "May 16": "16 ພຶດສະພາ",
  "May 17": "17 ພຶດສະພາ",
  "May 18": "18 ພຶດສະພາ",
  "May 18 - May 24, 2025": "18 - 24 ພຶດສະພາ 2025",
  "Business Dashboard": "ແດຊບອດທຸລະກິດ",
  "Overview of your business performance and operations.":
    "ພາບລວມຜົນງານ ແລະ ການດຳເນີນງານຂອງທຸລະກິດ.",
  "Help & Support": "ຊ່ວຍເຫຼືອ & Support",
  "Visit Help Center": "ໄປສູນຊ່ວຍເຫຼືອ",
  "Guides, tutorials, and articles": "ຄູ່ມື, ວິທີໃຊ້ງານ ແລະ ບົດຄວາມ",
  "Contact Support": "ຕິດຕໍ່ Support",
  "Get help from our team": "ຮັບຄວາມຊ່ວຍເຫຼືອຈາກທີມງານ",
  "What's New": "ມີຫຍັງໃໝ່",
  "See latest features and updates": "ເບິ່ງ feature ແລະ update ຫຼ້າສຸດ",
  "Recent Orders": "ອໍເດີຫຼ້າສຸດ",
  "View all orders": "ເບິ່ງອໍເດີທັງໝົດ",
  "Order #": "ເລກອໍເດີ",
  Customer: "ລູກຄ້າ",
  Amount: "ຈຳນວນເງິນ",
  Time: "ເວລາ",
  Preparing: "ກຳລັງກຽມ",
  "Business at a Glance": "ພາບລວມທຸລະກິດ",
  "Taxes Collected": "ພາສີທີ່ເກັບໄດ້",
  "Discounts Given": "ສ່ວນຫຼຸດທີ່ໃຫ້",
  Refunds: "ການຄືນເງິນ",
  "Net Sales": "ຍອດຂາຍສຸດທິ",
  "Top Selling Items": "ສິນຄ້າຂາຍດີ",
  "Inventory Alerts": "ແຈ້ງເຕືອນສະຕັອກ",
  "Branch Performance": "ຜົນງານສາຂາ",
  Critical: "ວິກິດ",
  Low: "ຕ່ຳ",
  "vs last week": "ທຽບກັບອາທິດກ່ອນ",
  "Main Branch": "ສາຂາຫຼັກ",
  "Sihom Branch": "ສາຂາສີຫອມ",
  "Tha Dong Branch": "ສາຂາທ່າດົງ",
  "Pak Ngum Branch": "ສາຂາປາກງື່ມ",
  "Fresh Milk 1L": "ນົມສົດ 1L",
  Croissant: "ຄຣົວຊອງ",
  "Brown Sugar Syrup": "ນ້ຳເຊື່ອມນ້ຳຕານແດງ",
  "Coffee Beans": "ເມັດກາເຟ",
  "Paper Cup 12oz": "ຈອກເຈ້ຍ 12oz",
  "Appointment Calendar": "ປະຕິທິນນັດໝາຍ",
  "Manage your salon appointments and schedule.": "ຈັດການນັດໝາຍ ແລະ ຕາຕະລາງຂອງຮ້ານ.",
  "New Appointment": "ສ້າງນັດໝາຍ",
  Filters: "ກັ່ນຕອງ",
  Week: "ອາທິດ",
  "All Areas": "ທຸກໂຊນ",
  "Nail Zone": "ໂຊນເລັບ",
  "Hair Station": "ສະຖານີຜົມ",
  "Spa Room 1": "ຫ້ອງສະປາ 1",
  "Spa Room 2": "ຫ້ອງສະປາ 2",
  "VIP Room": "ຫ້ອງ VIP",
  Working: "ກຳລັງເຮັດວຽກ",
  "Day Off": "ມື້ພັກ",
  "Time Off": "ພັກຊົ່ວຄາວ",
  "Nail Tech": "ຊ່າງເລັບ",
  "Hair Stylist": "ຊ່າງຜົມ",
  Therapist: "ນັກບຳບັດ",
  "Hair Cut": "ຕັດຜົມ",
  "Hair Cut & Blow Dry": "ຕັດຜົມ & ເປົ່າຜົມ",
  "Hair Cut & Blow": "ຕັດຜົມ & ເປົ່າຜົມ",
  "Hair Coloring": "ຍ້ອມຜົມ",
  "Hair Treatment": "ບຳລຸງຜົມ",
  "Acrylic Extension": "ຕໍ່ເລັບ Acrylic",
  "Gel Polish": "ທາສີເລັບ Gel",
  Manicure: "ແຕ່ງເລັບມື",
  Pedicure: "ແຕ່ງເລັບຕີນ",
  "Thai Massage": "ນວດໄທ",
  "Aroma Massage": "ນວດ Aroma",
  "Facial Treatment": "ບຳລຸງໜ້າ",
  "Eye Brow Shaping": "ແຕ່ງຄິ້ວ",
  Hair: "ຜົມ",
  Nail: "ເລັບ",
  "Spa & Body": "ສະປາ & ຮ່າງກາຍ",
  Face: "ໃບໜ້າ",
  "Hair Care Package": "ແພັກເກດດູແລຜົມ",
  "Nail Lover Package": "ແພັກເກດຄົນຮັກເລັບ",
  "Thai Massage Package": "ແພັກເກດນວດໄທ",
  "Facial Glow Package": "ແພັກເກດໜ້າໃສ",
  "Track room stays and booking timelines.": "ຕິດຕາມການພັກ ແລະ timeline ການຈອງຫ້ອງ.",
  "All Rooms": "ຫ້ອງທັງໝົດ",
  "By Floor": "ຕາມຊັ້ນ",
  "By Room Type": "ຕາມປະເພດຫ້ອງ",
  "Room List": "ລາຍຊື່ຫ້ອງ",
  "Room Types": "ປະເພດຫ້ອງ",
  "Search room...": "ຄົ້ນຫາຫ້ອງ...",
  Room: "ຫ້ອງ",
  "Room Type": "ປະເພດຫ້ອງ",
  Floor: "ຊັ້ນ",
  Actions: "ການດຳເນີນການ",
  Booked: "ຈອງແລ້ວ",
  Blocked: "ບລັອກ",
  Occupied: "ມີແຂກພັກ",
  Vacant: "ວ່າງ",
  Clean: "ສະອາດ",
  Dirty: "ຕ້ອງທຳຄວາມສະອາດ",
  Inspected: "ກວດແລ້ວ",
  Stayover: "ພັກຕໍ່",
  Maintenance: "ສ້ອມບຳລຸງ",
  "Standard King": "ຫ້ອງ Standard King",
  "Standard Twin": "ຫ້ອງ Standard Twin",
  "Deluxe King": "ຫ້ອງ Deluxe King",
  "Deluxe Twin": "ຫ້ອງ Deluxe Twin",
  "Superior King": "ຫ້ອງ Superior King",
  "Superior Twin": "ຫ້ອງ Superior Twin",
  "Family Room": "ຫ້ອງຄອບຄົວ",
  Suite: "ຫ້ອງ Suite",
  "1st Floor": "ຊັ້ນ 1",
  "2nd Floor": "ຊັ້ນ 2",
  "3rd Floor": "ຊັ້ນ 3",
  "Room Settings & Housekeeping": "ຕັ້ງຄ່າຫ້ອງ & ແມ່ບ້ານ",
  "Manage rooms, room types, and housekeeping status.":
    "ຈັດການຫ້ອງ, ປະເພດຫ້ອງ ແລະ ສະຖານະແມ່ບ້ານ.",
  "Booking List": "ລາຍການຈອງ",
  "View and manage all bookings.": "ເບິ່ງ ແລະ ຈັດການການຈອງທັງໝົດ.",
  Subtotal: "ຍອດກ່ອນຄ່າບໍລິການ",
  "Service Charge (10%)": "ຄ່າບໍລິການ (10%)",
  "Tax (VAT 10%)": "ພາສີ (VAT 10%)",
  Rounding: "ປັດເສດ",
  Rate: "ອັດຕາ",
  Percentage: "ເປີເຊັນ",
  "Round to nearest 100 LAK": "ປັດໃກ້ສຸດ 100 LAK",
  "Source Table": "ໂຕະຕົ້ນທາງ",
  Destination: "ປາຍທາງ",
  "Destination Table": "ໂຕະປາຍທາງ",
  "Order Amount": "ຍອດອໍເດີ",
  From: "ຈາກ",
  To: "ໄປຫາ",
  Duration: "ໄລຍະເວລາ",
  Indoor: "ໃນຮ້ານ",
  Terrace: "ລະບຽງ",
  "Private Room": "ຫ້ອງສ່ວນຕົວ",
  "Food Sales": "ຍອດຂາຍອາຫານ",
  "Beverage Sales": "ຍອດຂາຍເຄື່ອງດື່ມ",
  "Mobile / QR": "Mobile / QR",
  "Top Items Sold": "ລາຍການຂາຍດີ",
  "Closed By": "ປິດໂດຍ",
  "Restaurant closed at 11:30 PM": "ຮ້ານປິດເວລາ 11:30 PM",
  "All cash deposited": "ນຳເງິນສົດຝາກຄົບແລ້ວ",
  "One void order reviewed by manager": "ຜູ້ຈັດການກວດອໍເດີທີ່ void 1 ລາຍການແລ້ວ",
  "Iced Latte": "ລາເຕ້ເຢັນ",
  "Whole Milk": "ນົມສົດ",
  "Oat Milk": "ນົມໂອດ",
  Almond: "ອາມອນ",
  Soy: "ນົມຖົ່ວເຫຼືອງ",
  "Sweetness Level": "ລະດັບຄວາມຫວານ",
  "Extra Shot +3,000": "ເພີ່ມ Shot +3,000",
  "Vanilla Syrup +2,000": "ນ້ຳເຊື່ອມ Vanilla +2,000",
  "Caramel Syrup +2,000": "ນ້ຳເຊື່ອມ Caramel +2,000",
  "Afternoon Delight": "Afternoon Delight",
  Beverages: "ເຄື່ອງດື່ມ",
  Pastries: "ເບເກີຣີ",
  Food: "ອາຫານ",
  Others: "ອື່ນໆ",
  "Export Report": "ສົ່ງອອກລາຍງານ",
  Order: "Order",
  Station: "Station"
};

export function toLaoText(value: string) {
  return (laoLabels[value] ?? value)
    .replace(/\bMay\b/g, "ພຶດສະພາ")
    .replace(/\bTotal\b/g, "ລວມ")
    .replace(/\bAvailable\b/g, "ວ່າງ")
    .replace(/\bActive\b/g, "ເປີດໃຊ້")
    .replace(/\bReady\b/g, "ພ້ອມ");
}

export function toLaoNode(value: ReactNode) {
  return typeof value === "string" ? toLaoText(value) : value;
}
