const laoLabels: Record<string, string> = {
  "Ready": "ພ້ອມ",
  "Pairing": "ກຳລັງຈັບຄູ່",
  "Connected": "ເຊື່ອມຕໍ່ແລ້ວ",
  "Counter": "ເຄົາເຕີ",
  "Order": "ອໍເດີ",
  "Cash": "ເງິນສົດ",
  "Bank Transfer": "ໂອນທະນາຄານ",
  "QR Code": "QR Code",
  "Card": "ບັດ",
  "Iced Latte": "ລາເຕ້ເຢັນ",
  "Hot Latte": "ລາເຕ້ຮ້ອນ",
  "Croissant": "ຄຣົວຊອງ",
  "Club Sandwich": "ແຊນວິດຄລັບ",
  "Subtotal": "ຍອດກ່ອນຫຼຸດ",
  "Service Charge (5%)": "ຄ່າບໍລິການ (5%)",
  "Discount": "ສ່ວນຫຼຸດ",
  "Total Due": "ຍອດຕ້ອງຊຳລະ",
  "Bank Name:": "ຊື່ທະນາຄານ:",
  "Account Name:": "ຊື່ບັນຊີ:",
  "Account No.:": "ເລກບັນຊີ:",
  "Reference:": "ອ້າງອີງ:",
  "Bank Transfer Details": "ລາຍລະອຽດການໂອນ",
  "Payment Method": "ວິທີຊຳລະ",
  "Welcome to TJ POS": "ຍິນດີຕ້ອນຮັບສູ່ TJ POS",
  "Your order details will appear here during checkout.": "ລາຍລະອຽດອໍເດີຈະສະແດງຢູ່ນີ້ຕອນຊຳລະ.",
  "We Accept": "ຮອງຮັບການຊຳລະ",
  "Multiple payment options for your convenience.": "ມີຫຼາຍວິທີຊຳລະເພື່ອຄວາມສະດວກ.",
  "All payments are secure and protected.": "ການຊຳລະທຸກລາຍການປອດໄພ ແລະ ຖືກປົກປ້ອງ.",
  "Please review your order on this screen during payment.": "ກະລຸນາກວດອໍເດີໃນໜ້າຈໍນີ້ລະຫວ່າງການຊຳລະ.",
  "This customer display updates automatically from the cashier POS.": "ຈໍລູກຄ້ານີ້ອັບເດດຈາກ POS ແຄັດເຊຍອັດຕະໂນມັດ.",
  "Review Your Order": "ກວດອໍເດີຂອງທ່ານ",
  "Please confirm your items before payment.": "ກະລຸນາກວດລາຍການກ່ອນຊຳລະ.",
  "QR Code is available and ready": "QR Code ພ້ອມໃຊ້ງານ",
  "Please review your order on the cashier screen": "ກະລຸນາກວດອໍເດີໃນໜ້າຈໍແຄັດເຊຍ",
  "Tap nothing here - this display is for customer viewing only.": "ບໍ່ຕ້ອງແຕະໜ້າຈໍນີ້ - ເປັນຈໍໃຫ້ລູກຄ້າເບິ່ງເທົ່ານັ້ນ.",
  "Scan to Pay": "ສະແກນເພື່ອຊຳລະ",
  "Please complete your payment using QR code or bank transfer.": "ກະລຸນາຊຳລະດ້ວຍ QR Code ຫຼື ໂອນທະນາຄານ.",
  "Scan with your banking app": "ສະແກນດ້ວຍແອັບທະນາຄານ",
  "Secure payment - Powered by TJ POS": "ຊຳລະປອດໄພ - Powered by TJ POS",
  "After payment, please wait for cashier confirmation.": "ຫຼັງຈາກຊຳລະແລ້ວ ກະລຸນາລໍຖ້າແຄັດເຊຍຢືນຢັນ.",
  "Thank you for your payment!": "ຂອບໃຈສຳລັບການຊຳລະ!",
  "Paid Amount": "ຈຳນວນທີ່ຈ່າຍ",
  "Order No.": "ເລກອໍເດີ",
  "Status": "ສະຖານະ",
  "Completed": "ສຳເລັດ",
  "Payment Successful": "ຊຳລະສຳເລັດ",
  "Thank you for your purchase!": "ຂອບໃຈສຳລັບການອຸດໜູນ!",
  "Please keep your receipt and wait for your order.": "ກະລຸນາເກັບບິນ ແລະ ລໍຖ້າອໍເດີ.",
  "Thank you and enjoy your meal!": "ຂອບໃຈ ແລະ ຂໍໃຫ້ອາຫານອະລ່ອຍ!",
  "We appreciate your visit and hope to see you again soon.": "ຂອບໃຈທີ່ມາໃຊ້ບໍລິການ ແລະ ຫວັງວ່າຈະໄດ້ພົບກັນອີກ.",
  "Pair Customer Display": "ຈັບຄູ່ຈໍລູກຄ້າ",
  "Connect this display to the cashier POS device for live order and payment updates.": "ເຊື່ອມຈໍນີ້ກັບ POS ແຄັດເຊຍເພື່ອອັບເດດອໍເດີ ແລະ ການຊຳລະສົດ.",
  "Counter Display": "ຈໍເຄົາເຕີ",
  "Live POS Sync": "Sync ກັບ POS ສົດ",
  "Secure Session": "Session ປອດໄພ",
  "Pairing Code": "ລະຫັດຈັບຄູ່",
  "Waiting for POS device confirmation": "ກຳລັງລໍຖ້າອຸປະກອນ POS ຢືນຢັນ",
  "Item": "ລາຍການ",
  "Quantity": "ຈຳນວນ",
  "Unit Price": "ລາຄາຕໍ່ໜ່ວຍ",
  "Amount": "ຈຳນວນເງິນ"
};

export function lo(value: string) {
  return laoLabels[value] ?? value;
}
