const laoLabels: Record<string, string> = {
  "Good Coffee, Good Day": "ກາເຟດີ ມື້ດີ",
  "Lane Xang Avenue": "ຖະໜົນລ້ານຊ້າງ",
  "Vientiane Capital, Laos": "ນະຄອນຫຼວງວຽງຈັນ, ລາວ",
  "Closes 10:00 PM": "ປິດ 22:00",
  "All": "ທັງໝົດ",
  "Coffee": "ກາເຟ",
  "Signature": "ເມນູແນະນຳ",
  "Tea": "ຊາ",
  "Food": "ອາຫານ",
  "All Coffee": "ກາເຟທັງໝົດ",
  "Hot Coffee": "ກາເຟຮ້ອນ",
  "Iced Coffee": "ກາເຟເຢັນ",
  "Frappe": "ປັ່ນ",
  "All Menu": "ເມນູທັງໝົດ",
  "Menu": "ເມນູ",
  "Info": "ຂໍ້ມູນ",
  "Call": "ໂທ",
  "Search menu...": "ຄົ້ນຫາເມນູ...",
  "Clear search": "ລ້າງການຄົ້ນຫາ",
  "Cancel": "ຍົກເລີກ",
  "Search": "ຄົ້ນຫາ",
  "Table": "ໂຕະ",
  "Dine In": "ນັ່ງກິນທີ່ຮ້ານ",
  "Today": "ມື້ນີ້",
  "Open": "ເປີດ",
  "Freshly brewed for you": "ຊົງສົດໃໝ່ເພື່ອທ່ານ",
  "Quality ingredients, great taste.": "ວັດຖຸດິບດີ ລົດຊາດດີ.",
  "Out of Stock": "ສິນຄ້າໝົດ",
  "Out": "ໝົດ",
  "Best Seller": "ຂາຍດີ",
  "Photos": "ຮູບພາບ",
  "Call Staff": "ເອີ້ນພະນັກງານ",
  "Store Info": "ຂໍ້ມູນຮ້ານ",
  "Categories": "ໝວດໝູ່",
  "View all": "ເບິ່ງທັງໝົດ",
  "Popular Picks": "ເມນູຍອດນິຍົມ",
  "Back to store": "ກັບໄປໜ້າຮ້ານ",
  "Browse menu items, prices, availability and store details.": "ເບິ່ງເມນູ, ລາຄາ, ສະຖານະສິນຄ້າ ແລະ ຂໍ້ມູນຮ້ານ.",
  "No items available": "ບໍ່ມີລາຍການ",
  "Please choose another category.": "ກະລຸນາເລືອກໝວດໝູ່ອື່ນ.",
  "Back to menu": "ກັບໄປເມນູ",
  "Share item": "ແຊຣ໌ລາຍການ",
  "Share": "ແຊຣ໌",
  "Category": "ໝວດໝູ່",
  "Size": "ຂະໜາດ",
  "Ingredients": "ສ່ວນປະກອບ",
  "Allergens": "ສານກໍ່ແພ້",
  "This is a digital menu item. Please place your order with our staff.": "ນີ້ແມ່ນເມນູດິຈິຕອນ. ກະລຸນາສັ່ງກັບພະນັກງານ.",
  "Temporarily unavailable": "ຍັງບໍ່ພ້ອມຂາຍຊົ່ວຄາວ",
  "Sorry, this item is currently out of stock. Please try another item.": "ຂໍອະໄພ, ລາຍການນີ້ໝົດຊົ່ວຄາວ. ກະລຸນາເລືອກລາຍການອື່ນ.",
  "Thank you for visiting us!": "ຂອບໃຈທີ່ມາໃຊ້ບໍລິການ!",
  "Opening Hours": "ເວລາເປີດຮ້ານ",
  "Monday - Friday": "ຈັນ - ສຸກ",
  "Saturday - Sunday": "ເສົາ - ອາທິດ",
  "About Us": "ກ່ຽວກັບຮ້ານ",
  "TJ Cafe Vientiane serves quality coffee, delicious drinks, and tasty food in a cozy and welcoming atmosphere.": "TJ Cafe Vientiane ໃຫ້ບໍລິການກາເຟຄຸນນະພາບ, ເຄື່ອງດື່ມອະລ່ອຍ ແລະ ອາຫານລົດຊາດດີ ໃນບັນຍາກາດອົບອຸ່ນ.",
  "Facilities": "ສິ່ງອຳນວຍຄວາມສະດວກ",
  "Free Wi-Fi, Power Outlets, Air Condition": "Wi-Fi ຟຣີ, ປັກໄຟ, ແອເຢັນ",
  "Payment": "ການຊຳລະ",
  "Cash, Card, LAK QR": "ເງິນສົດ, ບັດ, LAK QR",
  "Note": "ໝາຍເຫດ",
  "Prices are inclusive of VAT.": "ລາຄາລວມ VAT ແລ້ວ.",
  "Please contact staff to confirm booking availability.": "ກະລຸນາຕິດຕໍ່ພະນັກງານເພື່ອຢືນຢັນການຈອງ.",
  "Booking Request": "ຄຳຂໍຈອງ",
  "Booking can be enabled for supported businesses. This public menu stays view-only and does not create orders or payments.": "ການຈອງສາມາດເປີດໃຊ້ສຳລັບທຸລະກິດທີ່ຮອງຮັບ. ເມນູ public ນີ້ໃຊ້ເບິ່ງເທົ່ານັ້ນ ບໍ່ສ້າງອໍເດີ ຫຼື ການຊຳລະ.",
  "This QR opens the linked public menu for table": "QR ນີ້ເປີດເມນູ public ທີ່ຜູກກັບໂຕະ",
  "Open linked menu": "ເປີດເມນູທີ່ຜູກໄວ້",
  "results found": "ຜົນການຄົ້ນຫາ",
  "No menu found": "ບໍ່ພົບເມນູ",
  "Try another keyword or clear the search.": "ລອງຄຳຄົ້ນຫາອື່ນ ຫຼື ລ້າງການຄົ້ນຫາ.",
  "This is a digital menu. Please order with our staff.": "ນີ້ແມ່ນເມນູດິຈິຕອນ. ກະລຸນາສັ່ງກັບພະນັກງານ.",
  "Iced Latte": "ລາເຕ້ເຢັນ",
  "Smooth espresso with fresh milk over ice.": "Espresso ນຸ່ມກັບນົມສົດແລະນ້ຳແຂງ.",
  "Americano": "ອາເມຣິກາໂນ",
  "Rich and bold espresso diluted with hot water.": "Espresso ເຂັ້ມຂົ້ນຜະສົມນ້ຳຮ້ອນ.",
  "Cappuccino": "ຄາປູຊິໂນ",
  "Espresso with steamed milk and milk foam.": "Espresso ກັບນົມຮ້ອນ ແລະ ໂຟມນົມ.",
  "Caramel Macchiato": "ຄາຣາເມວ ມັກຄີອາໂຕ",
  "Vanilla milk with espresso and caramel drizzle.": "ນົມວານິລາກັບ Espresso ແລະ ຄາຣາເມວ.",
  "Mocha": "ໂມຄາ",
  "Chocolate and espresso with steamed milk.": "ຊັອກໂກແລັດ ແລະ Espresso ກັບນົມຮ້ອນ.",
  "Matcha Latte": "ມັດຊະ ລາເຕ້",
  "Premium matcha with steamed milk.": "Matcha ຄຸນນະພາບກັບນົມຮ້ອນ.",
  "Hot Latte": "ລາເຕ້ຮ້ອນ",
  "Espresso with steamed milk.": "Espresso ກັບນົມຮ້ອນ.",
  "Strawberry Frappe": "ສະຕໍເບີຣີປັ່ນ",
  "Blended strawberry with milk and ice, topped with whipped cream.": "ສະຕໍເບີຣີປັ່ນກັບນົມ ແລະ ນ້ຳແຂງ ພ້ອມ whipped cream.",
  "Butter Croissant": "ຄຣົວຊອງເນີຍ",
  "Flaky butter croissant baked fresh for coffee pairing.": "ຄຣົວຊອງເນີຍອົບສົດ ເໝາະກັບກາເຟ.",
  "Espresso, Fresh Milk, Ice": "Espresso, ນົມສົດ, ນ້ຳແຂງ",
  "Espresso, Hot Water": "Espresso, ນ້ຳຮ້ອນ",
  "Espresso, Steamed Milk, Foam": "Espresso, ນົມຮ້ອນ, ໂຟມ",
  "Espresso, Milk, Vanilla, Caramel": "Espresso, ນົມ, ວານິລາ, ຄາຣາເມວ",
  "Espresso, Cocoa, Milk": "Espresso, Cocoa, ນົມ",
  "Matcha, Milk": "Matcha, ນົມ",
  "Espresso, Steamed Milk": "Espresso, ນົມຮ້ອນ",
  "Strawberry, Milk, Ice, Whipped Cream": "ສະຕໍເບີຣີ, ນົມ, ນ້ຳແຂງ, whipped cream",
  "Flour, Butter, Milk, Egg": "ແປ້ງ, ເນີຍ, ນົມ, ໄຂ່",
  "Milk": "ນົມ",
  "None": "ບໍ່ມີ",
  "Milk, Egg, Gluten": "ນົມ, ໄຂ່, Gluten",
  "1 piece": "1 ອັນ",
  "A perfect balance of bold and creamy.": "ສົມດຸນລົດຊາດເຂັ້ມແລະນຸ່ມ."
};

export function lo(value: string) {
  return laoLabels[value] ?? value;
}
