const laoLabels: Record<string, string> = {
  "All Items": "ສິນຄ້າທັງໝົດ",
  "Coffee": "ກາເຟ",
  "Non Coffee": "ບໍ່ແມ່ນກາເຟ",
  "Tea": "ຊາ",
  "Pastry & Bakery": "ເບເກີຣີ",
  "Snacks": "ອາຫານວ່າງ",
  "Combos": "ຊຸດຄອມໂບ",
  "Beverages": "ເຄື່ອງດື່ມ",
  "Add-ons": "ເພີ່ມເຕີມ",
  "Iced Latte": "ລາເຕ້ເຢັນ",
  "Americano": "ອາເມຣິກາໂນ",
  "Cappuccino": "ຄາປູຊິໂນ",
  "Thai Milk Tea": "ຊານົມໄທ",
  "Croissant": "ຄຣົວຊອງ",
  "Chocolate Cake": "ເຄັກຊັອກໂກແລັດ",
  "Club Sandwich": "ແຊນວິດຄລັບ",
  "Mineral Water": "ນ້ຳດື່ມ",
  "Cola Can": "ໂຄລາກະປ໋ອງ",
  "Sprite Can": "ສະໄປຣທ໌ກະປ໋ອງ",
  "Orange Juice": "ນ້ຳສົ້ມ",
  "Green Tea": "ຊາຂຽວ",
  "Latte Caramel": "ລາເຕ້ຄາຣາເມວ",
  "Mocha": "ໂມຄາ",
  "Hot Latte": "ລາເຕ້ຮ້ອນ",
  "Affogato": "ອາຟໂຟກາໂຕ",
  "Flat White": "Flat White",
  "Cold Brew": "Cold Brew",
  "Cart": "ກະຕ່າ",
  "Clear": "ລ້າງ",
  "Cart is empty": "ຍັງບໍ່ມີສິນຄ້າໃນກະຕ່າ",
  "Add items from the product grid to start a sale.": "ເລືອກສິນຄ້າຈາກລາຍການເພື່ອເລີ່ມຂາຍ.",
  "Customer": "ລູກຄ້າ",
  "Discount": "ສ່ວນຫຼຸດ",
  "Subtotal": "ຍອດກ່ອນຫຼຸດ",
  "Tax (10%)": "ອາກອນ (10%)",
  "Tax": "ອາກອນ",
  "Total": "ລວມທັງໝົດ",
  "Pay": "ຊຳລະ",
  "Counter": "ເຄົາເຕີ",
  "No Table": "ບໍ່ເລືອກໂຕະ",
  "Dine In": "ນັ່ງກິນທີ່ຮ້ານ",
  "Take Away": "ສັ່ງກັບບ້ານ",
  "retail": "ຂາຍຍ່ອຍ",
  "wholesale": "ຂາຍສົ່ງ",
  "reseller": "ຜູ້ຂາຍຕໍ່",
  "Wholesale at": "ລາຄາສົ່ງເມື່ອຊື້",
  "pcs": "ອັນ",
  "price": "ລາຄາ",
  "Note": "ໝາຍເຫດ",
  "No sesame": "ບໍ່ໃສ່ງາ",
  "Extra pearl": "ເພີ່ມໄຂ່ມຸກ",
  "Order Summary": "ສະຫຼຸບອໍເດີ",
  "Received Now": "ຮັບເງິນຕອນນີ້",
  "Debt Balance": "ຍອດໜີ້",
  "Change": "ເງິນທອນ",
  "Payment Method": "ວິທີຊຳລະ",
  "Cash": "ເງິນສົດ",
  "Card": "ບັດ",
  "Bank Transfer": "ໂອນທະນາຄານ",
  "QR Code": "QR Code",
  "e-Wallet": "e-Wallet",
  "Paid": "ຈ່າຍແລ້ວ",
  "Partial": "ຈ່າຍບາງສ່ວນ",
  "Debt": "ຕິດໜີ້",
  "Full payment now": "ຈ່າຍເຕັມຈຳນວນທັນທີ",
  "Pay part now": "ຈ່າຍບາງສ່ວນກ່ອນ",
  "Customer pays later": "ລູກຄ້າຈ່າຍພາຍຫຼັງ",
  "Debt checkout requires a customer profile with credit terms.": "ການຂາຍເປັນໜີ້ຕ້ອງເລືອກລູກຄ້າທີ່ມີເງື່ອນໄຂເຄຣດິດ.",
  "Split Payment": "ແບ່ງການຊຳລະ",
  "Back to Cart": "ກັບໄປກະຕ່າ",
  "Save Debt": "ບັນທຶກໜີ້",
  "Confirm Payment": "ຢືນຢັນການຊຳລະ",
  "Order Info": "ຂໍ້ມູນອໍເດີ",
  "Order ID": "ເລກອໍເດີ",
  "New Order": "ອໍເດີໃໝ່",
  "Table": "ໂຕະ",
  "Type": "ປະເພດ",
  "Cashier": "ແຄັດເຊຍ",
  "Items": "ລາຍການ",
  "Payment Status": "ສະຖານະຊຳລະ",
  "Paid Now": "ຈ່າຍແລ້ວ",
  "Walk-in Customer": "ລູກຄ້າທົ່ວໄປ",
  "No member selected": "ຍັງບໍ່ເລືອກສະມາຊິກ",
  "Limit": "ວົງເງິນ",
  "Payment Successful": "ຊຳລະສຳເລັດ",
  "Debt Saved": "ບັນທຶກໜີ້ແລ້ວ",
  "Partial Payment Saved": "ບັນທຶກການຈ່າຍບາງສ່ວນແລ້ວ",
  "The last paid order is not available.": "ບໍ່ພົບອໍເດີທີ່ຊຳລະຫຼ້າສຸດ.",
  "is ready to print.": "ພ້ອມພິມແລ້ວ.",
  "Print Bill": "ພິມບິນ",
  "New Sale": "ການຂາຍໃໝ່",
  "Refund / Return": "ຄືນເງິນ / ຄືນສິນຄ້າ",
  "Search receipt, select items, and confirm refund approval.": "ຄົ້ນຫາບິນ, ເລືອກລາຍການ ແລະ ຢືນຢັນອະນຸມັດຄືນເງິນ.",
  "Search receipt number or customer": "ຄົ້ນຫາເລກບິນ ຫຼື ລູກຄ້າ",
  "Find Receipt": "ຄົ້ນຫາບິນ",
  "No completed receipt selected.": "ຍັງບໍ່ເລືອກບິນທີ່ສຳເລັດ.",
  "Refund Summary": "ສະຫຼຸບການຄືນເງິນ",
  "Receipt": "ບິນ",
  "Refund Items": "ລາຍການຄືນ",
  "Refund Amount": "ຈຳນວນເງິນຄືນ",
  "Approval": "ອະນຸມັດ",
  "Manager required": "ຕ້ອງໃຫ້ຜູ້ຈັດການອະນຸມັດ",
  "Confirm Refund": "ຢືນຢັນຄືນເງິນ",
  "Cancel": "ຍົກເລີກ",
  "Payment": "ການຊຳລະ",
  "Time": "ເວລາ",
  "Back to POS": "ກັບໄປ POS",
  "Open Orders": "ອໍເດີເປີດຢູ່",
  "Held Orders": "ອໍເດີພັກໄວ້",
  "Completed": "ສຳເລັດ",
  "Grid": "ຕາຕະລາງ",
  "List": "ລາຍການ",
  "Search order, table, or customer": "ຄົ້ນຫາອໍເດີ, ໂຕະ ຫຼື ລູກຄ້າ",
  "Refresh": "ໂຫຼດໃໝ່",
  "Order": "ອໍເດີ",
  "orders": "ອໍເດີ",
  "Table / Type": "ໂຕະ / ປະເພດ",
  "Amount": "ຈຳນວນເງິນ",
  "Action": "ການດຳເນີນການ",
  "No orders match this view.": "ບໍ່ມີອໍເດີທີ່ກົງກັບມຸມມອງນີ້.",
  "Open": "ເປີດ",
  "Search item or scan barcode": "ຄົ້ນຫາສິນຄ້າ ຫຼື ສະແກນ Barcode",
  "Branch": "ສາຂາ",
  "Shift": "ກະ",
  "Online": "ອອນລາຍ",
  "Open terminal menu": "ເປີດເມນູ Terminal",
  "Terminal menu will open here.": "ເມນູ Terminal ຈະເປີດຢູ່ນີ້.",
  "Hold Order": "ພັກອໍເດີ",
  "Table / Dine In": "ໂຕະ / ນັ່ງກິນ",
  "More": "ເພີ່ມເຕີມ",
  "Scanning barcode": "ສະແກນ Barcode",
  "Scan or type SKU": "ສະແກນ ຫຼື ພິມ SKU",
  "Try CF-1001, BK-3001, or TE-2001.": "ລອງ CF-1001, BK-3001 ຫຼື TE-2001.",
  "Add Item": "ເພີ່ມສິນຄ້າ",
  "Apply Discount": "ໃຊ້ສ່ວນຫຼຸດ",
  "Discount Mode": "ຮູບແບບສ່ວນຫຼຸດ",
  "By Percent (%)": "ຕາມເປີເຊັນ (%)",
  "By Amount (LAK)": "ຕາມຈຳນວນເງິນ (LAK)",
  "Discount Value": "ມູນຄ່າສ່ວນຫຼຸດ",
  "Reason": "ເຫດຜົນ",
  "Member Discount": "ສ່ວນຫຼຸດສະມາຊິກ",
  "Manager Approval": "ຜູ້ຈັດການອະນຸມັດ",
  "Promotion Campaign": "ແຄມເປນໂປຣໂມຊັນ",
  "Current Order": "ອໍເດີປັດຈຸບັນ",
  "Current Total": "ຍອດປັດຈຸບັນ",
  "Select Customer": "ເລືອກລູກຄ້າ",
  "Search by name, phone, or member ID": "ຄົ້ນຫາຕາມຊື່, ເບີໂທ ຫຼື Member ID",
  "Points": "ແຕ້ມ",
  "New Customer": "ລູກຄ້າໃໝ່",
  "Select Table": "ເລືອກໂຕະ",
  "Search table": "ຄົ້ນຫາໂຕະ",
  "Floor": "ແຜນຜັງຮ້ານ",
  "All Areas": "ທຸກໂຊນ",
  "Indoor": "ພາຍໃນ",
  "Outdoor": "ພາຍນອກ",
  "VIP Room": "ຫ້ອງ VIP",
  "Terrace": "ລານນອກ",
  "Seats": "ບ່ອນນັ່ງ",
  "Available": "ວ່າງ",
  "Occupied": "ມີລູກຄ້າ",
  "Reserved": "ຈອງໄວ້",
  "In Progress": "ກຳລັງເຮັດ",
  "Held": "ພັກໄວ້"
};

const customerTypeLabels: Record<string, string> = {
  retail: "ຂາຍຍ່ອຍ",
  wholesale: "ຂາຍສົ່ງ",
  reseller: "ຜູ້ຂາຍຕໍ່",
  vip: "VIP"
};

const paymentStatusLabels: Record<string, string> = {
  paid: "ຈ່າຍແລ້ວ",
  partial: "ຈ່າຍບາງສ່ວນ",
  debt: "ຕິດໜີ້"
};

export function lo(value: string) {
  return laoLabels[value] ?? value;
}

export function loCustomerType(value: string) {
  return customerTypeLabels[value] ?? lo(value);
}

export function loPaymentStatus(value: string) {
  return paymentStatusLabels[value] ?? lo(value);
}
